apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: na1djjb7x-dotnet-basic 
  janus-idp.io/tekton: na1djjb7x-dotnet-basic
  backstage.io/kubernetes-id: na1djjb7x-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: na1djjb7x-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  