apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: na1djjb7x-dotnet-basic-gitops-repository
spec:
  url: https://github.com/testrhtaporg/na1djjb7x-dotnet-basic-gitops